<?php

/**
 * Implements hook_form_alter
 */

function application_edit_form_webform_client_form_1_alter(&$form, &$form_state, $form_id)
{
  /*
  $courseid = $_GET['course'] ?? null;

  //Remove options outside of the current date range.
  $nodes = node_load_multiple(array(), array('type' => 'course'));
  foreach ($nodes as $course) {
    $datestart = field_get_items('node', $course, 'field_application_date')[0]['value'] ?? null;
    $dateend = field_get_items('node', $course, 'field_application_date')[0]['value2'] ?? null;
    if (strtotime($datestart) > time() || strtotime($dateend) < time()) {
      unset($form['submitted']['course']['#options'][$course->nid]);
    }
  }

  if ($courseid) {
    $course = node_load($courseid);

    //Disable course id field.
    //$form['submitted']['course']['#disabled'] = true;
    //$description = field_get_items('node', $course, 'body')[0]['value'] ?? null;

    $datestart = field_get_items('node', $course, 'field_application_date')[0]['value'] ?? null;
    $dateend = field_get_items('node', $course, 'field_application_date')[0]['value2'] ?? null;

    //Add check for dates.
    if (strtotime($datestart) > time() && strtotime($dateend) < time()) {
      // Throw to the course page
      drupal_set_message('This course is not available for applying', 'error');
      drupal_goto('node/' . $courseid);
    }

    //$form['submitted']['course_description']['#value'] = $description;
    //$form['submitted']['application_period']['#value'] = format_date(strtotime($datestart), 'only_date') . ' — ' . format_date(strtotime($dateend), 'only_date');
  }
  */
}

function application_edit_preprocess_node(&$variables)
{
  if ($variables['type'] == 'webform') {
    $variables['submitted'] = '';
  }
  /*
  $datestart = $variables['field_application_date']['und'][0]['value'] ?? null;
  $dateend = $variables['field_application_date']['und'][0]['value2'] ?? null;
  if (strtotime($datestart) > time() || strtotime($dateend) < time()) {
    hide($variables['content']['field_link_to_webform']);
  }*/
}

function application_edit_views_post_execute(&$view)
{
  /*
  if ($view->name == 'course_catalogue') {
    foreach ($view->result as $course) {
      $datestart = $course->field_field_application_date[0]['raw']['value'] ?? null;
      $dateend = $course->field_field_application_date[0]['raw']['value2'] ?? null;
      if (strtotime($datestart) > time() || strtotime($dateend) < time()) {
        //$course->field_field_application_date[0]['rendered']['#markup'] .= "<h2><a href='node/1?course=$course->nid'>Apply for this course ></a></h2>";
        unset($course->field_field_link_to_webform);
      }
    }
  }
  */
}
